name: ZeMarketSystem
main: de.db.market.MarketPlugin
version: 1.0
author: ZeBobbel

commands:
  market:
    description: Main command for the market system.
    usage: /market <subcommand>
    aliases: [m]
  'yes':
    description: Confirms an action.
    usage: /yes
  'no':
    description: Cancels an action.
    usage: /no